#!/usr/bin/env bash
# render-queue.sh — render sketches STRICTLY one at a time.
#
# Renders are CPU-bound through SwiftShader, so two at once do not take the time
# of one, they take longer than both in sequence. Backgrounding several jobs that
# each wait for the renderer to be free does not serialise them either: they all
# see an idle machine at the same moment and start together. One script, one
# loop, no concurrency.
#
# Do NOT edit this file while it is running - bash reads a script incrementally,
# so changing the byte offsets mid-run can make it misparse the rest. Stop it,
# edit, restart.
#
#   bash scripts/paint/render-queue.sh
set -u
cd "$(dirname "$0")/../.."

# sketch : out-dir/name : size : seed : extra flags
JOBS=(
  "plate-ceiling:art/spread-ceiling:1500x1050:9:--bleed"
  "plate-rouge-shift:art/spread-rouge-shift:1500x1000:2:--bleed"
  "plate-roc:art/spread-roc:1500x1100:8:--bleed"
)

for job in "${JOBS[@]}"; do
  IFS=: read -r sketch out size seed flags <<< "$job"
  echo "── $out"
  if node scripts/paint/render.mjs "sketches/$sketch.js" --size "$size" --seed "$seed" $flags \
       --out "public/images/$out.png"; then
    # Transparent marks need alpha preserved at full quality or the soft edge
    # they exist for turns into a halo.
    if [[ "$flags" == *--transparent* ]]; then
      cwebp -q 88 -alpha_q 100 -quiet "public/images/$out.png" -o "public/images/$out.webp"
    else
      cwebp -q 88 -quiet "public/images/$out.png" -o "public/images/$out.webp"
    fi
    echo "   -> public/images/$out.webp"
  else
    echo "   FAILED: $out"
  fi
done
echo "QUEUE DONE"
